"""Add total_battles and wins to Player

Revision ID: 8cc70ff406b7
Revises: ebee776dfe33
Create Date: 2025-06-11 12:25:50.676620

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8cc70ff406b7'
down_revision: Union[str, None] = 'ebee776dfe33'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('players', sa.Column('total_battles', sa.Integer(), nullable=False))
    op.add_column('players', sa.Column('wins', sa.Integer(), nullable=False))
    op.alter_column('players', 'level',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('players', 'experience',
               existing_type=sa.INTEGER(),
               type_=sa.Float(),
               nullable=False)
    op.alter_column('players', 'money',
               existing_type=sa.INTEGER(),
               type_=sa.Float(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('players', 'money',
               existing_type=sa.Float(),
               type_=sa.INTEGER(),
               nullable=True)
    op.alter_column('players', 'experience',
               existing_type=sa.Float(),
               type_=sa.INTEGER(),
               nullable=True)
    op.alter_column('players', 'level',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('players', 'wins')
    op.drop_column('players', 'total_battles')
    # ### end Alembic commands ###
